### ISSUE TITLE
后端能不能弄成PHP的？

### ISSUE THREAD

**Issue by arenj** [hua1995116/webchat#1]
无奈不懂nodejs啊。后端能不能换成PHP的？数据库换成MYSQL？

**Comment by hua1995116** [comment]
php我没研究，mysql的话就两张表，
user表
name: {unique: true,type: String }, password: String,src: String,meta: {createAt: {type: Date,default:Date.now() }, updateAt: { type: Date,default: Date.now() }}
message表
username: String,src: String,msg: { type: String, default: '' },roomid: String, img: {type: String, default: '' }, time: {type: Date,default: Date.now() }
