### ISSUE TITLE
 bug

### ISSUE THREAD

**Issue by sunshine940326** [hua1995116/webchat#14]
http://www.qiufengh.com:9090/#/ 这个下面的
已经注册好了，但是登录不上，输入完账号密码之后点击登录就没有然后了。。。就没有然后了。。。。还是登录的页面
然后注册的时候，会弹出空对话框，不知道是账号重复了还是密码格式有问题，空对话框没有内容

**Comment by hua1995116** [comment]
提供账号看看。

**Comment by sunshine940326** [comment]
sunshine940326

**Comment by hua1995116** [comment]
这个是之前的一个问题，已经修复了的
