### ISSUE TITLE
大佬你背景图不见了。

### ISSUE THREAD

**Issue by zsychy** [hua1995116/webchat#18]
大佬你背景图不见了，除了个透明图标看不到其他东西了。。以为挂了

**Comment by zsychy** [comment]
博客好像也打不开了。。是不是针对我。。刚才还可以的。。

**Comment by hua1995116** [comment]
都可以了，刚才在发版

**Comment by zsychy** [comment]
好的大佬但是我下载下来运行不起来。说我没有打开数据库连接。。但是我之前。。。没用过芒果。。

**Comment by hua1995116** [comment]
你需要先装MongoDb的。去官网下一个把

**Comment by zsychy** [comment]
大佬在吗。方便加下扣扣啥的么。。我的是984249214
