### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by pandajojo** [hua1995116/webchat#23]
今天下午打开 可以登录注册 但是不能发送信息，而且会报一大堆的错误

**Comment by pandajojo** [comment]
我把项目clone下来   把地址改成自己的也开了数据库 在本地可以运行 数据库信息也可以写入 但是别人访问我的地址的时候就会报错 （他们可以注册登录 但是就是发送不了信息）

**Comment by hua1995116** [comment]
你是说，你那边搭建的项目出了问题是么。请问你改socket的链接了么

**Comment by pandajojo** [comment]
我用的内网  所以把你的项目网址改成自己电脑的ip地址了  socket的链接在哪里改呢

**Comment by pandajojo** [comment]
然后连接我电脑的也是做我旁边同一内网的小伙伴 他可以注册登录 就是不能发信息  一发送信息他那边就会报错 说是refused

**Comment by hua1995116** [comment]
是在这样的。在这个文件下/src/view/Loan.vue，43行，this.$store.commit('setGetSocket', io.connect('http://www.qiufengh.com:9090/'))。你看是不是不一致导致

**Comment by pandajojo** [comment]
我改的就是这个文件if (!this.getSocket) {
        if (process.env.NODE_ENV === 'development') {
          this.$store.commit('setGetSocket', io.connect('localhost:9090/'))
        } else {
          this.$store.commit('setGetSocket', io.connect('10.35.167.92:9090/'))
        }

**Comment by pandajojo** [comment]
我是把下面改成了自己电脑的IP地址  按道理说同一内网的应该是可以访问的啊   注册登录都没有问题  他们的账号数据库也保存了 就是发送信息这里出了问题

**Comment by hua1995116** [comment]
你截图看看，报了什么错。内网应该没关系，只要都是访问你的ip，映射到你启动的服务就好了。

**Comment by pandajojo** [comment]
稍等  我去开下数据库  启动下服务

**Comment by hua1995116** [comment]
你加下我q把。461249104
