### ISSUE TITLE
可以添加一个你的项目结构的注释吗 我想了解关于后端是如何搭建的

### ISSUE THREAD

**Issue by cdpv587** [hua1995116/webchat#25]
可以添加一个你的项目结构的注释吗 我想了解关于后端是如何搭建的

**Comment by hua1995116** [comment]
你是指后端api是吧，可以的，尽快加上，好了，我在这边和你说。，最近有点忙，需要一点时间哈，1-2天。

**Comment by cdpv587** [comment]
好  多谢

**Comment by hua1995116** [comment]
你好，我在master主分支，写了上后端接口的api，你看是否可以参考一下，有问题联系我。

**Comment by hua1995116** [comment]
@cdpv587
