### ISSUE TITLE
执行npm run dev报错

### ISSUE THREAD

**Issue by whwangp** [hua1995116/webchat#28]
请帮忙查看一下为什么启动不了，执行npm run dev的时候报错
<img width="745" alt="image" src="https://user-images.githubusercontent.com/31472308/38715916-98880d3e-3f10-11e8-811f-8d98b4644b23.png">

**Comment by hua1995116** [comment]
你没启动mongodb把。

**Comment by whwangp** [comment]
已经好了，的确，我本地没有安装mongodb，多谢啦

**Comment by hua1995116** [comment]
把issue 关了吧
