### ISSUE TITLE
关注下，安卓手机的物理返回键，或是PC端调试的时候点击的浏览器返回键

### ISSUE THREAD

**Issue by bleilei** [hua1995116/webchat#5]
安卓上点击返回键，在四个tab页中，页面返回历史没有问题，可是tab的active class没有变化。弹出的聊天室，点击返回之后页面不关闭，直接在后面进行返回了，当前页面显示一直是聊天室。

**Comment by hua1995116** [comment]
你好，感谢你的提问，你问题的原理是这样的。我这个聊天页面，我设置了一个全局的浮动页面，并没有把它加入到路由操作中，所以出现了你上述问题，我会进行整改，感谢支持。
