### ISSUE TITLE
安装问题

### ISSUE THREAD

**Issue by tadli** [hua1995116/webchat#51]
按你提供的指导
npm install -----安装依赖

npm run dev -----运行

自动打开的页面无法获取到
需要在哪个位置修改参数吗？

**Comment by hua1995116** [comment]
你是不是没有安装MongoDB数据库？ @tadli

**Comment by tadli** [comment]
有装的，并且在运行前，已经先启动mongod运行中的

**Comment by tadli** [comment]
These dependencies were not found:

* babel-runtime/regenerator in ./src/store/index.js, ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./src/view/Loan.vue and 6 others
* babel-runtime/helpers/asyncToGenerator in ./src/store/index.js, ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./src/view/Loan.vue and 6 others
* babel-runtime/helpers/toConsumableArray in ./src/store/index.js
* babel-runtime/core-js/promise in ./src/components/photo-viewer/index.js, ./src/api/axios.js and 3 others
* babel-runtime/core-js/number/max-safe-integer in ./src/utils/localStorage.js
* babel-runtime/core-js/json/stringify in ./src/utils/localStorage.js, ./src/api/axios.js
* babel-runtime/helpers/extends in ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./src/App.vue, ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./src/view/Loan.vue and 5 others

**Comment by tadli** [comment]
npm install babel-runtime@6
就可以修复安装问题：）

**Comment by hua1995116** [comment]
我在本地调试了下这个问题，因为我本地用的是cnpm，一开始以为是cnpm的原因，但是发现npm也是可以的正常开发的。
然后来看下为什么我本地是没有问题的，可以看到我的package.json中并没有显示声明babel-runtime的依赖，是因为我有下载babel-plugin-transform-runtime，而有依赖下载babel-runtime，因为知道在npm3后，node_modules下面都成了扁平结构，去除了一些重复的包，扁平化意味着其他的包可以相互依赖，从而导致我这边因为babel-plugin-transform-runtime的副作用有了babel-runtime。但是这种副作用的方式确实不太好，现在我已经将babel-runtime添加到了package.json中。
