### ISSUE TITLE
imagemin-pngquant包安装问题

### ISSUE THREAD

**Issue by lumos102** [hua1995116/webchat#64]
请问下您这边有遇到过`imagemin-pngquant`包安装出错的问题吗？提示说pngquant-bin包的postinstall钩子有问题：Failed at the pngquant-bin@5.0.2 postinstall script

**Comment by hua1995116** [comment]
麻烦给下具体信息。因为那几个包是依赖底层几个库的，是很容易出问题。在 centos 需要安装几个包 https://github.com/imagemin/imagemin-pngquant/issues/40

**Comment by lumos102** [comment]
就是运行npm run dev的时候会报找不到`imagemin-pngquant`找不到，然后npm i这个包，就会报pngquant-bin的错误：Failed at the pngquant-bin@5.0.2 postinstall script。是不是因为这里涉及的npm包的扁平化处理

**Comment by hua1995116** [comment]
https://github.com/kornelski/pngquant/issues/166  具体 issue 是这个
