### ISSUE TITLE
哥们报错一下问题怎么解决呀

### ISSUE THREAD

**Issue by Francis-LvYang** [hua1995116/webchat#67]
dledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Exited with code 3
(node:1369) [DEP0018] DeprecationWarning: Unhandled promise rejections are dep
我的redis和服务都运行起来了，mongodb也连接上了，就是这出现了问题

**Comment by hua1995116** [comment]
还有更详细的错误吗。

**Comment by Francis-LvYang** [comment]
npm run dev后就报这个错误，然后聊天室里面一直刷新状态，控制台报错跨域，我看看是不是跨域问题

**Comment by hua1995116** [comment]
你 pull 下代码吧。

**Comment by Francis-LvYang** [comment]
(node:7284) DeprecationWarning: `open()` is deprecated in mongoose >= 4.11.0, use `openUri()` instead, or set the `useMongoClient` option if using `connect()` or `createConnection()`. See http://mongoosejs.com/docs/4.x/docs/connections.html#use-mongo-client

**Comment by hua1995116** [comment]
这个不是报错。只是一个 warning。

**Comment by Francis-LvYang** [comment]
然后就报这个
![image](https://user-images.githubusercontent.com/25260780/56092905-f364a000-5ef4-11e9-86df-b72deb58aa73.png)

**Comment by Francis-LvYang** [comment]
大概意思说不能处理这个回调？
